version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: robobudget
      POSTGRES_PASSWORD: robobudget
      POSTGRES_DB: robobudget
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: robobudget
      MONGO_INITDB_ROOT_PASSWORD: robobudget
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_URL=postgres://robobudget:robobudget@postgres:5432/robobudget
      - MONGODB_URL=mongodb://robobudget:robobudget@mongodb:27017
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - mongodb
      - redis

  auth_service:
    build:
      context: ./services/auth_service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://robobudget:robobudget@postgres:5432/robobudget_auth
      - REDIS_URL=redis://redis:6379
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  mongodb_data:
  redis_data:
